### PR TITLE
Support for uploading files

### PR DESCRIPTION
**Pull request by alexkwolfe**
I rebased https://github.com/slackhq/node-slack-client/pull/22 on master and fixed up a few of the issues mentioned in that PR.

Also of note is that file uploading is now done with a multipart request. I'm allowing the caller to override the `token` param, which is [essential for performing a file upload from a bot](https://twitter.com/alexkwolfe/status/619176068600041472). Bots cannot do file uploads so a real user's API token must be provided.

```coffeescript
# Here's what a createFile call looks like
client.createFile file: '/home/user/smiley.png', token: 'xxxx-xxxxxxxx-xxxxxxxx', channels:'panic room', (result) ->
  console.log(result)
```

I'm looking for feedback on this PR and am happy to make adjustments, etc.

### CODE REVIEW

**Comment by meteormanaged** [comment]
any hope in getting this merged?

**Comment by Tehnix** [comment]
This would be awesome to have support for! Any updates on what is missing, if anything is?

**Comment by meteormanaged** [comment]
email address is in the user object

Mike Kozak
mkozak@meteormanaged.com<mailto:mkozak@meteormanaged.com>

On Oct 14, 2015, at 6:55 PM, Christian Kjaer <notifications@github.com<mailto:notifications@github.com>> wrote:


This would be awesome to have support for! Any updates on what is missing, if anything is?

-

**Comment by SJAnderson** [comment]
any word on this getting merged?

**Comment by halkeye** [comment]
@alexkwolfe do you have time to fix the merge conflicts? I want to start nudging people for this again but it seems like its no longer a clean merge. If you don't have time, lemme know and I'll take a stab.

**Comment by jeffclyne** [comment]
I'd love to see this merged as well so slackhq/hubot-slack#62 can proceed.

**Comment by l12s** [comment]
Can you link me to the hubot issue where that's discussed?

Right now, you can upload files via something like:

```
webClient.files.upload({
  file: ...,
  channels: ['...'],
});
```

The way the PR is currently structured would need to be changed around quite a bit, as the pattern of mixing the model objects with API actions (e.g. `file.setComments`) isn't one the `>= 2.0.x` client is going to support.

So, if the issue is the general one of getting an API call to use to upload files, that's pretty simple and I can add a full example to the `/examples` directory later today. If the richer support around file comments etc is needed, that'll take a while longer.

**Comment by jeffclyne** [comment]
I think the issue is just having an API call to use to upload files, so the `hubot-slack` adapter can provide the hook for scripts to utilize.

**Comment by l12s** [comment]
Gotcha. I'll write up a proper example this week. Thanks for the clarification.

**Comment by crookedneighbor** [comment]
Is this PR needed any more? I see an example for how to upload files in the example directory.

**Comment by DEGoodmanWilson** [comment]
I'm going to assume not—I'll open an issue to track this should it turn out that uploading files on 3.x isn't working so hot.

**Pull request closed without merging**
